// Mocks generated by Mockito 5.4.4 from annotations
// in kuvaka_expense_tracker/test/widget/transaction_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:kuvaka_expense_tracker/features/budget/model/budget_model.dart'
    as _i7;
import 'package:kuvaka_expense_tracker/features/budget/viewmodel/budget_provider.dart'
    as _i6;
import 'package:kuvaka_expense_tracker/features/transactions/model/transaction_model.dart'
    as _i3;
import 'package:kuvaka_expense_tracker/features/transactions/viewmodel/transaction_provider.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TransactionProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionProvider extends _i1.Mock
    implements _i2.TransactionProvider {
  MockTransactionProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Transaction> get transactions => (super.noSuchMethod(
        Invocation.getter(#transactions),
        returnValue: <_i3.Transaction>[],
      ) as List<_i3.Transaction>);

  @override
  double get totalIncome => (super.noSuchMethod(
        Invocation.getter(#totalIncome),
        returnValue: 0.0,
      ) as double);

  @override
  double get totalExpenses => (super.noSuchMethod(
        Invocation.getter(#totalExpenses),
        returnValue: 0.0,
      ) as double);

  @override
  double get currentBalance => (super.noSuchMethod(
        Invocation.getter(#currentBalance),
        returnValue: 0.0,
      ) as double);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> addTransaction(_i3.Transaction? tx) => (super.noSuchMethod(
        Invocation.method(
          #addTransaction,
          [tx],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateTransaction(_i3.Transaction? tx) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTransaction,
          [tx],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTransaction(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTransaction,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [BudgetProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockBudgetProvider extends _i1.Mock implements _i6.BudgetProvider {
  MockBudgetProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i7.Budget> get budgets => (super.noSuchMethod(
        Invocation.getter(#budgets),
        returnValue: <_i7.Budget>[],
      ) as List<_i7.Budget>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> addBudget(_i7.Budget? budget) => (super.noSuchMethod(
        Invocation.method(
          #addBudget,
          [budget],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateBudget(_i7.Budget? budget) => (super.noSuchMethod(
        Invocation.method(
          #updateBudget,
          [budget],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteBudget(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteBudget,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  double? getBudgetLimit(String? category) =>
      (super.noSuchMethod(Invocation.method(
        #getBudgetLimit,
        [category],
      )) as double?);

  @override
  bool isOverBudget(
    String? category,
    double? spent,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isOverBudget,
          [
            category,
            spent,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  double budgetUsageRatio(
    String? category,
    double? spent,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #budgetUsageRatio,
          [
            category,
            spent,
          ],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
